// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RHSystem_webapi;

#nullable disable

namespace RHSystem_webapi.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20221027220207_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("RHSystem_webapi.Folha", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("diasTrabalhados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idFuncionario")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idSetor")
                        .HasColumnType("INTEGER");

                    b.Property<double>("salario")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Folha");
                });

            modelBuilder.Entity("RHSystem_webapi.Funcionario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("sexo")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("RHSystem_webapi.Setor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<double>("valorDiaTrabalho")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Setor");
                });
#pragma warning restore 612, 618
        }
    }
}
